import type { Metadata } from 'next'
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClerkProvider>
          <header className="flex items-center justify-between px-6 h-16 border-b border-slate-700 bg-[#0f172a]">
  <div className="text-lg font-semibold text-white">
    ⚡ BidX
  </div>

  <div className="flex items-center gap-4">
    <Show when="signed-out">
      <SignInButton />
      <SignUpButton>
        <button className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-md">
          Sign Up
        </button>
      </SignUpButton>
    </Show>

    <Show when="signed-in">
      <UserButton />
    </Show>
  </div>
</header>
          {children}
        </ClerkProvider>
      </body>
    </html>
  )
}